//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.7
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. It should be kept private.
 */
public class AWSConfiguration {

    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 92ce83f4-eb55-4ef6-acde-ba4dfc7ea50b aws-my-sample-app-android-v0.7";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
        Regions.US_EAST_1;
    public static final String AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:2573c1a0-9a54-4df5-b215-9b1f76aadb65";
    public static final String AMAZON_CONTENT_DELIVERY_S3_BUCKET =
        "viking-contentdelivery-mobilehub-1292343291";
    public static final String AMAZON_CLOUD_FRONT_DISTRIBUTION_DOMAIN =
        "d2ay6otcrmnx8j.cloudfront.net";
}
